# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yash1610 # the name of your site, e.g. ACME Corp.
author: Yash Bhardwaj
email: yashb1610@gmail.com
tagline: This is my developer portfolio and doubles as a blog for my thoughts.
description: >- # this means to ignore newlines until "baseurl:"
  This website is my developer portfolio and doubles as a blog for my thoughts,
  all opinions are my own unless stated otherwise and do not represent the
  organizations / individuals associated with me. Any inferrence based
  on what I write here is invalid. Also I make lots of mistakes, so let
  me know about any errors you find.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yash1610.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  yash1610
steam_username:  yash1610
linkedin_username:  yash1610
twitter_username: yash_1610
youtube_username: UCvonxf0PagMxpMJhkp2h-oA
twitter:
  username: yash1610
  card: summary
social:
  name: Yash Bhardwaj
  links:
    - https://github.com/yash1610
    - https://www.linkedin.com/in/yash1610/
    - https://twitter.com/yash_1610
    - https://www.youtube.com/channel/UCvonxf0PagMxpMJhkp2h-oA
    - https://steamcommunity.com/id/yash1610
# pinterest_username: jekyll
rss: feed.xml
tags_page: "/articles/tags.html"

date_format: "%a %b %d %Y"

permalink: none

kramdown:
  parse_block_html: true
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
